os: unstable
environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: VM4yc2j2L3KS5qWLZLY7WUAXoqdB9YkodmXlHC2I+LSF0Y8a2cZ70M0+2+Fd5GkQ
  COVERALLS_REPO_TOKEN:
    secure: iDcAJCYgJK4tffyzEHbMVR8DatJcIN8eY0h29p9JQkl43TcEcm6Z6JLOBpGDk1MJ

  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"
  - nodejs_version: "8"
  - electron_version: "1.4.12"
    nodejs_version: "6"

platform:
- x86
- x64

# Dropping support for node 4 on 32 windows because it has isuses with ssl certs and npm
matrix:
  exclude:
    - platform: x86
      nodejs_version: "4"


install:
- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
- ps: $env:Path += ";$(pwd)\node_modules\.bin";
# work around bug in npm 2 where id doesn't like our dev dep peers
- ps: >
    if ($env:nodejs_version -eq "4") {
      npm install -g npm | Write-Host;
    }
    true;

- ps: >
    @{
      "nodejs_version" = $env:nodejs_version
      "platform" = $env:platform
      "node binary version" = $(node -v)
      "node platform@arch" = $(node -p 'process.platform + process.arch')
      "npm version" = $(npm -v)
      "APPVEYOR_REPO_COMMIT_MESSAGE" = $env:APPVEYOR_REPO_COMMIT_MESSAGE
      "git latest tag" = "$(git describe --tags --always HEAD)"
      "appveyor_repo_tag" = $env:appveyor_repo_tag
      "electron_version" = $env:electron_version
    } | Out-String | Write-Host;

# Check if we're building the latest tag, if so
# then we publish the binaries if tests pass.
- ps: >
    if ($env:appveyor_repo_tag -match "true" -and ("$(git describe --tags --always HEAD)" -eq $env:appveyor_repo_tag_name)) {
      $env:publish_binary = 1;
    } else {
      $env:publish_binary = 0;
    }
    true;

- ps: >
    if ($env:publish_binary -eq 1) {
      "We're publishing a binary!" | Write-Host
    } else {
      "We're not publishing a binary" | Write-Host
    }
    true;

# Cleanup the output of npm
- ps: >
    npm config set progress false
    npm config set spin false

# We don't currently have a port to test on windows
# - ps: $env:TEST_PORT = "COM1";

# Setup Electron variables
- ps: >
    if ($env:electron_version) {
      "We're an electron build, setup variables" | Write-Host
      $env:npm_config_target = $env:electron_version
      $env:npm_config_disturl = "https://atom.io/download/atom-shell"
      $env:npm_config_runtime = "electron"

      if ($env:plaftorm -eq "x86") {
        $env:npm_config_arch = "ia32"
      } else {
        $env:npm_config_arch = "x64"
      }

      "Install electron and electron-mocha" | Write-Host

      npm install -g electron@$env:electron_version
      npm install electron-mocha
    }
    true;

build_script:
- npm install --build-from-source --msvs_version=2013

test_script:
- ps: >
    if ($env:nodejs_version -ne "4") {
      npm run lint
    }
    true;

# If we run npm test in powershell it'll have the wrong encoding
# so we have to do it like this

- IF DEFINED electron_version (electron test/electron)
- IF NOT DEFINED electron_version (node ./)
- IF NOT DEFINED electron_version (npm test)

- IF %PUBLISH_BINARY% == 1 (node-pre-gyp package 2>&1)
- IF %PUBLISH_BINARY% == 1 (node-pre-gyp-github publish --release 2>&1)
- IF %PUBLISH_BINARY% == 1 (node-pre-gyp clean)
- IF %PUBLISH_BINARY% == 1 (npm install --fallback-to-build=false)

after_test:
- pip install codecov && codecov --file coverage\coverage.json

deploy: OFF
